language: node_js

node_js: 6

dist: trusty

sudo: false

before_install:
    - npm i -g npm@^6

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

install:
    - npm ci

script:
    - npm run validate-commits
    - npm run lint
    - npm run test:series -- --coverage

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
