language: node_js

node_js: 6

dist: trusty

sudo: false

before_install:
    - npm i -g npm@^6

install:
    - npm ci

script:
    - npm run validate-commits
    - npm run lint
    - npm run test:series -- --coverage
